export enum ApiErrorCode {
  // General
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_REQUEST = 'INVALID_REQUEST',
  SERVER_ERROR = 'SERVER_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  TIMEOUT = 'TIMEOUT',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  DEPENDENCY_FAILURE = 'DEPENDENCY_FAILURE',

  // Signup
  SIGNUP_EMAIL_ALREADY_EXISTS = 'SIGNUP_EMAIL_ALREADY_EXISTS',
  SIGNUP_USERNAME_TAKEN = 'SIGNUP_USERNAME_TAKEN',
  SIGNUP_WEAK_PASSWORD = 'SIGNUP_WEAK_PASSWORD',
  SIGNUP_INVALID_EMAIL = 'SIGNUP_INVALID_EMAIL',
  SIGNUP_TERMS_NOT_ACCEPTED = 'SIGNUP_TERMS_NOT_ACCEPTED',
  SIGNUP_CAPTCHA_FAILED = 'SIGNUP_CAPTCHA_FAILED',

  // Signin
  SIGNIN_INVALID_CREDENTIALS = 'SIGNIN_INVALID_CREDENTIALS',
  SIGNIN_ACCOUNT_LOCKED = 'SIGNIN_ACCOUNT_LOCKED',
  SIGNIN_ACCOUNT_NOT_VERIFIED = 'SIGNIN_ACCOUNT_NOT_VERIFIED',
  SIGNIN_TOO_MANY_ATTEMPTS = 'SIGNIN_TOO_MANY_ATTEMPTS',
  SIGNIN_MFA_REQUIRED = 'SIGNIN_MFA_REQUIRED',
  SIGNIN_MFA_INVALID = 'SIGNIN_MFA_INVALID',
  SIGNIN_EMAIL_NOT_VERIFIED = 'SIGNIN_EMAIL_NOT_VERIFIED',

  // Signout
  SIGNOUT_FAILED = 'SIGNOUT_FAILED',
  SIGNOUT_NOT_SIGNED_IN = 'SIGNOUT_NOT_SIGNED_IN',

  // Forgot Password
  FORGOT_PASSWORD_EMAIL_NOT_FOUND = 'FORGOT_PASSWORD_EMAIL_NOT_FOUND',
  FORGOT_PASSWORD_TOO_MANY_REQUESTS = 'FORGOT_PASSWORD_TOO_MANY_REQUESTS',
  FORGOT_PASSWORD_SERVICE_UNAVAILABLE = 'FORGOT_PASSWORD_SERVICE_UNAVAILABLE',

  // Reset Password
  RESET_PASSWORD_TOKEN_INVALID = 'RESET_PASSWORD_TOKEN_INVALID',
  RESET_PASSWORD_TOKEN_EXPIRED = 'RESET_PASSWORD_TOKEN_EXPIRED',
  RESET_PASSWORD_WEAK_PASSWORD = 'RESET_PASSWORD_WEAK_PASSWORD',
  RESET_PASSWORD_TOO_MANY_ATTEMPTS = 'RESET_PASSWORD_TOO_MANY_ATTEMPTS',
  RESET_PASSWORD_USER_NOT_FOUND = 'RESET_PASSWORD_USER_NOT_FOUND',

  // Verify Email
  VERIFY_EMAIL_TOKEN_INVALID = 'VERIFY_EMAIL_TOKEN_INVALID',
  VERIFY_EMAIL_TOKEN_EXPIRED = 'VERIFY_EMAIL_TOKEN_EXPIRED',
  VERIFY_EMAIL_ALREADY_VERIFIED = 'VERIFY_EMAIL_ALREADY_VERIFIED',
  VERIFY_EMAIL_TOO_MANY_REQUESTS = 'VERIFY_EMAIL_TOO_MANY_REQUESTS',
  VERIFY_EMAIL_USER_NOT_FOUND = 'VERIFY_EMAIL_USER_NOT_FOUND',

  // Send Verify Email
  SEND_VERIFY_EMAIL_FAILED = 'SEND_VERIFY_EMAIL_FAILED',
  SEND_VERIFY_EMAIL_TOO_MANY_REQUESTS = 'SEND_VERIFY_EMAIL_TOO_MANY_REQUESTS',
  SEND_VERIFY_EMAIL_USER_NOT_FOUND = 'SEND_VERIFY_EMAIL_USER_NOT_FOUND',
  SEND_VERIFY_EMAIL_INVALID_ADDRESS = 'SEND_VERIFY_EMAIL_INVALID_ADDRESS',
}
